# rEFInd configuration file
# Location: /EFI/refind/refind.conf

## Timeout and default selection
# Wait 20 seconds before booting the default
timeout 10
default_selection "Fedora"
use_graphics_for linux,windows
scan_all_linux_kernels

# Keep rEFInd independent of EFI NVRAM boot entries.
use_nvram true
icons_dir "themes/refind-efifetch/icons"
resolution max

## Scanning
# Enable & lock native resolution
enable_and_lock
scanfor internal,manual

menuentry "Windows" {
    icon "themes/refind-efifetch/icons/os_win10.png"
    loader "\\EFI\\Microsoft\\Boot\\bootmgfw.efi"
    ostype "Windows"
}

showtools reboot,shutdown
banner full_screen themes/refind-efifetch/background.png
banner_scale fillscreen
hideui labels,help

## Icon sizes
small_icon_size 64

selection_small themes/refind-efifetch/selection_small.png
# selection_big themes/refind-efifetch/selection_big.png


## Miscellaneous
textonly 0
timeout_quiet

include themes/refind-efifetch/theme.conf
