# Hide unnecessary UI
hideui badges,arrows,hints,label

# Icons
icons_dir themes/refind-efifetch/icons

# Background
banner themes/refind-efifetch/background.png
banner_scale fillscreen

# Icon sizes
small_icon_size 64
big_icon_size 128
selection_small themes/refind-efifetch/selection_small.png
selection_big themes/refind-efifetch/selection_big.png

# Graphics
use_graphics_for linux,grub,windows

# Only useful tools
showtools shutdown,firmware

# Only Fedora + Windows
max_tags 2

# Boot timeout
timeout 20
